#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLon
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="quanLyduan")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCategory(Category instance);
    partial void UpdateCategory(Category instance);
    partial void DeleteCategory(Category instance);
    partial void InserttblSinhVien(tblSinhVien instance);
    partial void UpdatetblSinhVien(tblSinhVien instance);
    partial void DeletetblSinhVien(tblSinhVien instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    partial void Inserttaikhoan(taikhoan instance);
    partial void Updatetaikhoan(taikhoan instance);
    partial void Deletetaikhoan(taikhoan instance);
    partial void InserttblDeTai(tblDeTai instance);
    partial void UpdatetblDeTai(tblDeTai instance);
    partial void DeletetblDeTai(tblDeTai instance);
    partial void InserttblGiangVien(tblGiangVien instance);
    partial void UpdatetblGiangVien(tblGiangVien instance);
    partial void DeletetblGiangVien(tblGiangVien instance);
    partial void InserttblHuongDan(tblHuongDan instance);
    partial void UpdatetblHuongDan(tblHuongDan instance);
    partial void DeletetblHuongDan(tblHuongDan instance);
    partial void InserttblKhoa(tblKhoa instance);
    partial void UpdatetblKhoa(tblKhoa instance);
    partial void DeletetblKhoa(tblKhoa instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::BaiTapLon.Properties.Settings.Default.quanLyduanConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Category> Categories
		{
			get
			{
				return this.GetTable<Category>();
			}
		}
		
		public System.Data.Linq.Table<tblSinhVien> tblSinhViens
		{
			get
			{
				return this.GetTable<tblSinhVien>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<taikhoan> taikhoans
		{
			get
			{
				return this.GetTable<taikhoan>();
			}
		}
		
		public System.Data.Linq.Table<tblDeTai> tblDeTais
		{
			get
			{
				return this.GetTable<tblDeTai>();
			}
		}
		
		public System.Data.Linq.Table<tblGiangVien> tblGiangViens
		{
			get
			{
				return this.GetTable<tblGiangVien>();
			}
		}
		
		public System.Data.Linq.Table<tblHuongDan> tblHuongDans
		{
			get
			{
				return this.GetTable<tblHuongDan>();
			}
		}
		
		public System.Data.Linq.Table<tblKhoa> tblKhoas
		{
			get
			{
				return this.GetTable<tblKhoa>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Category")]
	public partial class Category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _Alias;
		
		private System.Nullable<int> _ParentID;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<int> _Order;
		
		private System.Nullable<bool> _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAliasChanging(string value);
    partial void OnAliasChanged();
    partial void OnParentIDChanging(System.Nullable<int> value);
    partial void OnParentIDChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnOrderChanging(System.Nullable<int> value);
    partial void OnOrderChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    #endregion
		
		public Category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alias", DbType="NVarChar(50)")]
		public string Alias
		{
			get
			{
				return this._Alias;
			}
			set
			{
				if ((this._Alias != value))
				{
					this.OnAliasChanging(value);
					this.SendPropertyChanging();
					this._Alias = value;
					this.SendPropertyChanged("Alias");
					this.OnAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
		public System.Nullable<int> ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this.OnParentIDChanging(value);
					this.SendPropertyChanging();
					this._ParentID = value;
					this.SendPropertyChanged("ParentID");
					this.OnParentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Order]", Storage="_Order", DbType="Int")]
		public System.Nullable<int> Order
		{
			get
			{
				return this._Order;
			}
			set
			{
				if ((this._Order != value))
				{
					this.OnOrderChanging(value);
					this.SendPropertyChanging();
					this._Order = value;
					this.SendPropertyChanged("Order");
					this.OnOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSinhVien")]
	public partial class tblSinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _sMaSV;
		
		private string _sHoten;
		
		private string _sMakhoa;
		
		private System.Nullable<System.DateTime> _dNgaysinh;
		
		private string _sGioitinh;
		
		private string _sQuequan;
		
		private EntityRef<tblHuongDan> _tblHuongDan;
		
		private EntityRef<tblKhoa> _tblKhoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsMaSVChanging(string value);
    partial void OnsMaSVChanged();
    partial void OnsHotenChanging(string value);
    partial void OnsHotenChanged();
    partial void OnsMakhoaChanging(string value);
    partial void OnsMakhoaChanged();
    partial void OndNgaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OndNgaysinhChanged();
    partial void OnsGioitinhChanging(string value);
    partial void OnsGioitinhChanged();
    partial void OnsQuequanChanging(string value);
    partial void OnsQuequanChanged();
    #endregion
		
		public tblSinhVien()
		{
			this._tblHuongDan = default(EntityRef<tblHuongDan>);
			this._tblKhoa = default(EntityRef<tblKhoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sMaSV", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string sMaSV
		{
			get
			{
				return this._sMaSV;
			}
			set
			{
				if ((this._sMaSV != value))
				{
					this.OnsMaSVChanging(value);
					this.SendPropertyChanging();
					this._sMaSV = value;
					this.SendPropertyChanged("sMaSV");
					this.OnsMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sHoten", DbType="NVarChar(30)")]
		public string sHoten
		{
			get
			{
				return this._sHoten;
			}
			set
			{
				if ((this._sHoten != value))
				{
					this.OnsHotenChanging(value);
					this.SendPropertyChanging();
					this._sHoten = value;
					this.SendPropertyChanged("sHoten");
					this.OnsHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sMakhoa", DbType="NVarChar(10)")]
		public string sMakhoa
		{
			get
			{
				return this._sMakhoa;
			}
			set
			{
				if ((this._sMakhoa != value))
				{
					if (this._tblKhoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsMakhoaChanging(value);
					this.SendPropertyChanging();
					this._sMakhoa = value;
					this.SendPropertyChanged("sMakhoa");
					this.OnsMakhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dNgaysinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> dNgaysinh
		{
			get
			{
				return this._dNgaysinh;
			}
			set
			{
				if ((this._dNgaysinh != value))
				{
					this.OndNgaysinhChanging(value);
					this.SendPropertyChanging();
					this._dNgaysinh = value;
					this.SendPropertyChanged("dNgaysinh");
					this.OndNgaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sGioitinh", DbType="NVarChar(3)")]
		public string sGioitinh
		{
			get
			{
				return this._sGioitinh;
			}
			set
			{
				if ((this._sGioitinh != value))
				{
					this.OnsGioitinhChanging(value);
					this.SendPropertyChanging();
					this._sGioitinh = value;
					this.SendPropertyChanged("sGioitinh");
					this.OnsGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sQuequan", DbType="NVarChar(100)")]
		public string sQuequan
		{
			get
			{
				return this._sQuequan;
			}
			set
			{
				if ((this._sQuequan != value))
				{
					this.OnsQuequanChanging(value);
					this.SendPropertyChanging();
					this._sQuequan = value;
					this.SendPropertyChanged("sQuequan");
					this.OnsQuequanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSinhVien_tblHuongDan", Storage="_tblHuongDan", ThisKey="sMaSV", OtherKey="sMasv", IsUnique=true, IsForeignKey=false)]
		public tblHuongDan tblHuongDan
		{
			get
			{
				return this._tblHuongDan.Entity;
			}
			set
			{
				tblHuongDan previousValue = this._tblHuongDan.Entity;
				if (((previousValue != value) 
							|| (this._tblHuongDan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHuongDan.Entity = null;
						previousValue.tblSinhVien = null;
					}
					this._tblHuongDan.Entity = value;
					if ((value != null))
					{
						value.tblSinhVien = this;
					}
					this.SendPropertyChanged("tblHuongDan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhoa_tblSinhVien", Storage="_tblKhoa", ThisKey="sMakhoa", OtherKey="sMakhoa", IsForeignKey=true)]
		public tblKhoa tblKhoa
		{
			get
			{
				return this._tblKhoa.Entity;
			}
			set
			{
				tblKhoa previousValue = this._tblKhoa.Entity;
				if (((previousValue != value) 
							|| (this._tblKhoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblKhoa.Entity = null;
						previousValue.tblSinhViens.Remove(this);
					}
					this._tblKhoa.Entity = value;
					if ((value != null))
					{
						value.tblSinhViens.Add(this);
						this._sMakhoa = value.sMakhoa;
					}
					else
					{
						this._sMakhoa = default(string);
					}
					this.SendPropertyChanged("tblKhoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _Alias;
		
		private System.Nullable<int> _CategoryID;
		
		private string _Images;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<decimal> _Price;
		
		private string _Detail;
		
		private System.Nullable<bool> _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAliasChanging(string value);
    partial void OnAliasChanged();
    partial void OnCategoryIDChanging(System.Nullable<int> value);
    partial void OnCategoryIDChanged();
    partial void OnImagesChanging(string value);
    partial void OnImagesChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnDetailChanging(string value);
    partial void OnDetailChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alias", DbType="NVarChar(50)")]
		public string Alias
		{
			get
			{
				return this._Alias;
			}
			set
			{
				if ((this._Alias != value))
				{
					this.OnAliasChanging(value);
					this.SendPropertyChanging();
					this._Alias = value;
					this.SendPropertyChanged("Alias");
					this.OnAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID", DbType="Int")]
		public System.Nullable<int> CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					this.OnCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._CategoryID = value;
					this.SendPropertyChanged("CategoryID");
					this.OnCategoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Images", DbType="NVarChar(250)")]
		public string Images
		{
			get
			{
				return this._Images;
			}
			set
			{
				if ((this._Images != value))
				{
					this.OnImagesChanging(value);
					this.SendPropertyChanging();
					this._Images = value;
					this.SendPropertyChanged("Images");
					this.OnImagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Detail
		{
			get
			{
				return this._Detail;
			}
			set
			{
				if ((this._Detail != value))
				{
					this.OnDetailChanging(value);
					this.SendPropertyChanging();
					this._Detail = value;
					this.SendPropertyChanged("Detail");
					this.OnDetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.taikhoan")]
	public partial class taikhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tenTK;
		
		private string _matkhau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntenTKChanging(string value);
    partial void OntenTKChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    #endregion
		
		public taikhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTK", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string tenTK
		{
			get
			{
				return this._tenTK;
			}
			set
			{
				if ((this._tenTK != value))
				{
					this.OntenTKChanging(value);
					this.SendPropertyChanging();
					this._tenTK = value;
					this.SendPropertyChanged("tenTK");
					this.OntenTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDeTai")]
	public partial class tblDeTai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _sMadt;
		
		private string _sTendt;
		
		private EntitySet<tblHuongDan> _tblHuongDans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsMadtChanging(string value);
    partial void OnsMadtChanged();
    partial void OnsTendtChanging(string value);
    partial void OnsTendtChanged();
    #endregion
		
		public tblDeTai()
		{
			this._tblHuongDans = new EntitySet<tblHuongDan>(new Action<tblHuongDan>(this.attach_tblHuongDans), new Action<tblHuongDan>(this.detach_tblHuongDans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sMadt", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string sMadt
		{
			get
			{
				return this._sMadt;
			}
			set
			{
				if ((this._sMadt != value))
				{
					this.OnsMadtChanging(value);
					this.SendPropertyChanging();
					this._sMadt = value;
					this.SendPropertyChanged("sMadt");
					this.OnsMadtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTendt", DbType="NVarChar(30)")]
		public string sTendt
		{
			get
			{
				return this._sTendt;
			}
			set
			{
				if ((this._sTendt != value))
				{
					this.OnsTendtChanging(value);
					this.SendPropertyChanging();
					this._sTendt = value;
					this.SendPropertyChanged("sTendt");
					this.OnsTendtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDeTai_tblHuongDan", Storage="_tblHuongDans", ThisKey="sMadt", OtherKey="sMadt")]
		public EntitySet<tblHuongDan> tblHuongDans
		{
			get
			{
				return this._tblHuongDans;
			}
			set
			{
				this._tblHuongDans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblHuongDans(tblHuongDan entity)
		{
			this.SendPropertyChanging();
			entity.tblDeTai = this;
		}
		
		private void detach_tblHuongDans(tblHuongDan entity)
		{
			this.SendPropertyChanging();
			entity.tblDeTai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblGiangVien")]
	public partial class tblGiangVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _sMaGV;
		
		private string _sMakhoa;
		
		private string _sTenGV;
		
		private string _sGT;
		
		private string _sSoDT;
		
		private string _taikhoan;
		
		private string _matkhau;
		
		private EntitySet<tblHuongDan> _tblHuongDans;
		
		private EntityRef<tblKhoa> _tblKhoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsMaGVChanging(string value);
    partial void OnsMaGVChanged();
    partial void OnsMakhoaChanging(string value);
    partial void OnsMakhoaChanged();
    partial void OnsTenGVChanging(string value);
    partial void OnsTenGVChanged();
    partial void OnsGTChanging(string value);
    partial void OnsGTChanged();
    partial void OnsSoDTChanging(string value);
    partial void OnsSoDTChanged();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    #endregion
		
		public tblGiangVien()
		{
			this._tblHuongDans = new EntitySet<tblHuongDan>(new Action<tblHuongDan>(this.attach_tblHuongDans), new Action<tblHuongDan>(this.detach_tblHuongDans));
			this._tblKhoa = default(EntityRef<tblKhoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sMaGV", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string sMaGV
		{
			get
			{
				return this._sMaGV;
			}
			set
			{
				if ((this._sMaGV != value))
				{
					this.OnsMaGVChanging(value);
					this.SendPropertyChanging();
					this._sMaGV = value;
					this.SendPropertyChanged("sMaGV");
					this.OnsMaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sMakhoa", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string sMakhoa
		{
			get
			{
				return this._sMakhoa;
			}
			set
			{
				if ((this._sMakhoa != value))
				{
					if (this._tblKhoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsMakhoaChanging(value);
					this.SendPropertyChanging();
					this._sMakhoa = value;
					this.SendPropertyChanged("sMakhoa");
					this.OnsMakhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTenGV", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string sTenGV
		{
			get
			{
				return this._sTenGV;
			}
			set
			{
				if ((this._sTenGV != value))
				{
					this.OnsTenGVChanging(value);
					this.SendPropertyChanging();
					this._sTenGV = value;
					this.SendPropertyChanged("sTenGV");
					this.OnsTenGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sGT", DbType="NVarChar(3)")]
		public string sGT
		{
			get
			{
				return this._sGT;
			}
			set
			{
				if ((this._sGT != value))
				{
					this.OnsGTChanging(value);
					this.SendPropertyChanging();
					this._sGT = value;
					this.SendPropertyChanged("sGT");
					this.OnsGTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sSoDT", DbType="NVarChar(10)")]
		public string sSoDT
		{
			get
			{
				return this._sSoDT;
			}
			set
			{
				if ((this._sSoDT != value))
				{
					this.OnsSoDTChanging(value);
					this.SendPropertyChanging();
					this._sSoDT = value;
					this.SendPropertyChanged("sSoDT");
					this.OnsSoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="NVarChar(50)")]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NVarChar(100)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblGiangVien_tblHuongDan", Storage="_tblHuongDans", ThisKey="sMaGV", OtherKey="sMagv")]
		public EntitySet<tblHuongDan> tblHuongDans
		{
			get
			{
				return this._tblHuongDans;
			}
			set
			{
				this._tblHuongDans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhoa_tblGiangVien", Storage="_tblKhoa", ThisKey="sMakhoa", OtherKey="sMakhoa", IsForeignKey=true)]
		public tblKhoa tblKhoa
		{
			get
			{
				return this._tblKhoa.Entity;
			}
			set
			{
				tblKhoa previousValue = this._tblKhoa.Entity;
				if (((previousValue != value) 
							|| (this._tblKhoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblKhoa.Entity = null;
						previousValue.tblGiangViens.Remove(this);
					}
					this._tblKhoa.Entity = value;
					if ((value != null))
					{
						value.tblGiangViens.Add(this);
						this._sMakhoa = value.sMakhoa;
					}
					else
					{
						this._sMakhoa = default(string);
					}
					this.SendPropertyChanged("tblKhoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblHuongDans(tblHuongDan entity)
		{
			this.SendPropertyChanging();
			entity.tblGiangVien = this;
		}
		
		private void detach_tblHuongDans(tblHuongDan entity)
		{
			this.SendPropertyChanging();
			entity.tblGiangVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblHuongDan")]
	public partial class tblHuongDan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _sMasv;
		
		private string _sMadt;
		
		private string _sMagv;
		
		private System.Nullable<System.DateTime> _dNgayBD;
		
		private System.Nullable<System.DateTime> _dNgayBaoCao;
		
		private string _sKetqua;
		
		private EntityRef<tblDeTai> _tblDeTai;
		
		private EntityRef<tblGiangVien> _tblGiangVien;
		
		private EntityRef<tblSinhVien> _tblSinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsMasvChanging(string value);
    partial void OnsMasvChanged();
    partial void OnsMadtChanging(string value);
    partial void OnsMadtChanged();
    partial void OnsMagvChanging(string value);
    partial void OnsMagvChanged();
    partial void OndNgayBDChanging(System.Nullable<System.DateTime> value);
    partial void OndNgayBDChanged();
    partial void OndNgayBaoCaoChanging(System.Nullable<System.DateTime> value);
    partial void OndNgayBaoCaoChanged();
    partial void OnsKetquaChanging(string value);
    partial void OnsKetquaChanged();
    #endregion
		
		public tblHuongDan()
		{
			this._tblDeTai = default(EntityRef<tblDeTai>);
			this._tblGiangVien = default(EntityRef<tblGiangVien>);
			this._tblSinhVien = default(EntityRef<tblSinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sMasv", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string sMasv
		{
			get
			{
				return this._sMasv;
			}
			set
			{
				if ((this._sMasv != value))
				{
					if (this._tblSinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsMasvChanging(value);
					this.SendPropertyChanging();
					this._sMasv = value;
					this.SendPropertyChanged("sMasv");
					this.OnsMasvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sMadt", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string sMadt
		{
			get
			{
				return this._sMadt;
			}
			set
			{
				if ((this._sMadt != value))
				{
					if (this._tblDeTai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsMadtChanging(value);
					this.SendPropertyChanging();
					this._sMadt = value;
					this.SendPropertyChanged("sMadt");
					this.OnsMadtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sMagv", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string sMagv
		{
			get
			{
				return this._sMagv;
			}
			set
			{
				if ((this._sMagv != value))
				{
					if (this._tblGiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsMagvChanging(value);
					this.SendPropertyChanging();
					this._sMagv = value;
					this.SendPropertyChanged("sMagv");
					this.OnsMagvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dNgayBD", DbType="DateTime")]
		public System.Nullable<System.DateTime> dNgayBD
		{
			get
			{
				return this._dNgayBD;
			}
			set
			{
				if ((this._dNgayBD != value))
				{
					this.OndNgayBDChanging(value);
					this.SendPropertyChanging();
					this._dNgayBD = value;
					this.SendPropertyChanged("dNgayBD");
					this.OndNgayBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dNgayBaoCao", DbType="DateTime")]
		public System.Nullable<System.DateTime> dNgayBaoCao
		{
			get
			{
				return this._dNgayBaoCao;
			}
			set
			{
				if ((this._dNgayBaoCao != value))
				{
					this.OndNgayBaoCaoChanging(value);
					this.SendPropertyChanging();
					this._dNgayBaoCao = value;
					this.SendPropertyChanged("dNgayBaoCao");
					this.OndNgayBaoCaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sKetqua", DbType="NVarChar(100)")]
		public string sKetqua
		{
			get
			{
				return this._sKetqua;
			}
			set
			{
				if ((this._sKetqua != value))
				{
					this.OnsKetquaChanging(value);
					this.SendPropertyChanging();
					this._sKetqua = value;
					this.SendPropertyChanged("sKetqua");
					this.OnsKetquaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDeTai_tblHuongDan", Storage="_tblDeTai", ThisKey="sMadt", OtherKey="sMadt", IsForeignKey=true)]
		public tblDeTai tblDeTai
		{
			get
			{
				return this._tblDeTai.Entity;
			}
			set
			{
				tblDeTai previousValue = this._tblDeTai.Entity;
				if (((previousValue != value) 
							|| (this._tblDeTai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDeTai.Entity = null;
						previousValue.tblHuongDans.Remove(this);
					}
					this._tblDeTai.Entity = value;
					if ((value != null))
					{
						value.tblHuongDans.Add(this);
						this._sMadt = value.sMadt;
					}
					else
					{
						this._sMadt = default(string);
					}
					this.SendPropertyChanged("tblDeTai");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblGiangVien_tblHuongDan", Storage="_tblGiangVien", ThisKey="sMagv", OtherKey="sMaGV", IsForeignKey=true)]
		public tblGiangVien tblGiangVien
		{
			get
			{
				return this._tblGiangVien.Entity;
			}
			set
			{
				tblGiangVien previousValue = this._tblGiangVien.Entity;
				if (((previousValue != value) 
							|| (this._tblGiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblGiangVien.Entity = null;
						previousValue.tblHuongDans.Remove(this);
					}
					this._tblGiangVien.Entity = value;
					if ((value != null))
					{
						value.tblHuongDans.Add(this);
						this._sMagv = value.sMaGV;
					}
					else
					{
						this._sMagv = default(string);
					}
					this.SendPropertyChanged("tblGiangVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSinhVien_tblHuongDan", Storage="_tblSinhVien", ThisKey="sMasv", OtherKey="sMaSV", IsForeignKey=true)]
		public tblSinhVien tblSinhVien
		{
			get
			{
				return this._tblSinhVien.Entity;
			}
			set
			{
				tblSinhVien previousValue = this._tblSinhVien.Entity;
				if (((previousValue != value) 
							|| (this._tblSinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSinhVien.Entity = null;
						previousValue.tblHuongDan = null;
					}
					this._tblSinhVien.Entity = value;
					if ((value != null))
					{
						value.tblHuongDan = this;
						this._sMasv = value.sMaSV;
					}
					else
					{
						this._sMasv = default(string);
					}
					this.SendPropertyChanged("tblSinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblKhoa")]
	public partial class tblKhoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _sMakhoa;
		
		private string _sTenkhoa;
		
		private string _sDienthoai;
		
		private string _sDiaChi;
		
		private EntitySet<tblSinhVien> _tblSinhViens;
		
		private EntitySet<tblGiangVien> _tblGiangViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsMakhoaChanging(string value);
    partial void OnsMakhoaChanged();
    partial void OnsTenkhoaChanging(string value);
    partial void OnsTenkhoaChanged();
    partial void OnsDienthoaiChanging(string value);
    partial void OnsDienthoaiChanged();
    partial void OnsDiaChiChanging(string value);
    partial void OnsDiaChiChanged();
    #endregion
		
		public tblKhoa()
		{
			this._tblSinhViens = new EntitySet<tblSinhVien>(new Action<tblSinhVien>(this.attach_tblSinhViens), new Action<tblSinhVien>(this.detach_tblSinhViens));
			this._tblGiangViens = new EntitySet<tblGiangVien>(new Action<tblGiangVien>(this.attach_tblGiangViens), new Action<tblGiangVien>(this.detach_tblGiangViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sMakhoa", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string sMakhoa
		{
			get
			{
				return this._sMakhoa;
			}
			set
			{
				if ((this._sMakhoa != value))
				{
					this.OnsMakhoaChanging(value);
					this.SendPropertyChanging();
					this._sMakhoa = value;
					this.SendPropertyChanged("sMakhoa");
					this.OnsMakhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTenkhoa", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string sTenkhoa
		{
			get
			{
				return this._sTenkhoa;
			}
			set
			{
				if ((this._sTenkhoa != value))
				{
					this.OnsTenkhoaChanging(value);
					this.SendPropertyChanging();
					this._sTenkhoa = value;
					this.SendPropertyChanged("sTenkhoa");
					this.OnsTenkhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sDienthoai", DbType="NVarChar(10)")]
		public string sDienthoai
		{
			get
			{
				return this._sDienthoai;
			}
			set
			{
				if ((this._sDienthoai != value))
				{
					this.OnsDienthoaiChanging(value);
					this.SendPropertyChanging();
					this._sDienthoai = value;
					this.SendPropertyChanged("sDienthoai");
					this.OnsDienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sDiaChi", DbType="NVarChar(50)")]
		public string sDiaChi
		{
			get
			{
				return this._sDiaChi;
			}
			set
			{
				if ((this._sDiaChi != value))
				{
					this.OnsDiaChiChanging(value);
					this.SendPropertyChanging();
					this._sDiaChi = value;
					this.SendPropertyChanged("sDiaChi");
					this.OnsDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhoa_tblSinhVien", Storage="_tblSinhViens", ThisKey="sMakhoa", OtherKey="sMakhoa")]
		public EntitySet<tblSinhVien> tblSinhViens
		{
			get
			{
				return this._tblSinhViens;
			}
			set
			{
				this._tblSinhViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhoa_tblGiangVien", Storage="_tblGiangViens", ThisKey="sMakhoa", OtherKey="sMakhoa")]
		public EntitySet<tblGiangVien> tblGiangViens
		{
			get
			{
				return this._tblGiangViens;
			}
			set
			{
				this._tblGiangViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSinhViens(tblSinhVien entity)
		{
			this.SendPropertyChanging();
			entity.tblKhoa = this;
		}
		
		private void detach_tblSinhViens(tblSinhVien entity)
		{
			this.SendPropertyChanging();
			entity.tblKhoa = null;
		}
		
		private void attach_tblGiangViens(tblGiangVien entity)
		{
			this.SendPropertyChanging();
			entity.tblKhoa = this;
		}
		
		private void detach_tblGiangViens(tblGiangVien entity)
		{
			this.SendPropertyChanging();
			entity.tblKhoa = null;
		}
	}
}
#pragma warning restore 1591
